name: Serialize Unturned maps and assets data

on:
  workflow_dispatch:


permissions:
  contents: write


jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: data
          path: data

      - name: Cache U3DS
        uses: actions/cache@v4
        with:
          path: U3DS
          key: u3ds-${{ hashFiles('U3DS') }}
          restore-keys: |
            u3ds

      - name: Debug
        run: |
          whoami
          pwd
          ls -la
          groups runner
          sudo chmod -R g+w ${{ github.workspace }}

      - name: Run Unturned data serializer
        run: |
          docker run -v ${{ github.workspace }}/U3DS:/app/U3DS -v ${{ github.workspace }}/data:/app/output ghcr.io/danielreker/unturned-data-serializer:latest

      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: data
          branch: data