name: Serialize Unturned maps and assets data

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"


permissions:
  contents: write


jobs:
  serialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: data
          path: data

      - name: Cache U3DS
        uses: actions/cache@v4
        with:
          path: U3DS
          key: u3ds
          restore-keys: |
            u3ds

      - name: Run Unturned data serializer
        run: |
          mkdir -p U3DS
          sudo chown -R 1000:1000 ${{ github.workspace }}/data ${{ github.workspace }}/U3DS
          docker run -v ${{ github.workspace }}/U3DS:/app/U3DS -v ${{ github.workspace }}/data:/app/output ghcr.io/danielreker/unturned-data-serializer:latest
          sudo chown -R $(id -u ${USER}):$(id -g ${USER}) ${{ github.workspace }}/data ${{ github.workspace }}/U3DS
      
      - name: Commit & Push changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: data
          branch: data
